ln -sf "${PWD}/symlink/zshrc" "$HOME/.zshrc"
ln -sf "${PWD}/symlink/zlogin" "$HOME/.zshrc"
ln -sf "${PWD}/symlink/aliases" "$HOME/.aliases"
ln -sf "${PWD}/symlink/gitignore" "$HOME/.gitignore"
ln -sf "${PWD}/symlink/gitconfig" "$HOME/.gitconfig"
ln -sf "${PWD}/symlink/vimrc" "$HOME/.vimrc"
