set encoding=utf-8

" display tabs and trailing whitespace
set listchars=trail:·,tab:→→
set list

" expand tabs to spaces
set expandtab
set tabstop=2
set softtabstop=2

" use two spaces for intendation
set shiftwidth=2

" unmap arrow keys
" noremap <Up> <nop>
" noremap <Down> <nop>
" noremap <Left> <nop>
" noremap <Right> <nop>

" syntax highlighting
syntax enable
