set nocompatible
set backspace=2
set encoding=utf-8

" Plugin-managed setup now lives in ~/.config/nvim/init.lua using lazy.nvim.

" allow usage of mouse
if has("mouse")
  set mouse=a
endif

" tab completion
set wildmode=longest,list
set wildmenu

" display tabs and trailing whitespace
set listchars=trail:·,tab:→→
set list

" expand tabs to spaces
set expandtab
set tabstop=2
set softtabstop=2

" use two spaces for indentation
set shiftwidth=2

" case insensitive search
set ignorecase
set smartcase

" incremental search with term highlighting
set incsearch
set hlsearch

" enable autoindent
set autoindent
set smartindent

" syntax highlighting
syntax enable

set laststatus=2 " always show status line
set cursorline " highlight the current line
set number " show line numbers

" remove "|" character from column separating vertical splits
set fillchars+=vert:\ 
hi VertSplit ctermbg=37

" show more information command bar
set showcmd
set ruler

" filetypes
filetype plugin indent on

autocmd BufNewFile,BufReadPost *.json set filetype=json
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" unmap arrow keys
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

" easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" easier access to esc key
inoremap jj <ESC>

" use mapleader as space
let mapleader = "\<Space>"

" spell checking
map <F4> :set spell!<CR><Bar>:echo "Spell Check: " . strpart("OffOn", 3 * &spell, 3)<CR>

" toggle :set paste / :set nopaste
set pastetoggle=<F10>

" toggle NERDTree
" Neovim maps <C-n> to NERDTreeTabsToggle via lazy.nvim.
