set nocompatible
set backspace=2
set encoding=utf-8

" load vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" let vundle manage vundle
Plugin 'gmarik/Vundle.vim'

" my vundle plugins
Plugin 'vim-syntastic/syntastic' " syntax checking
Plugin 'scrooloose/nerdtree' " tree explorer
Plugin 'jistr/vim-nerdtree-tabs' " same NERDTree across all tabs
Plugin 'tpope/vim-fugitive' " git wrapper
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-bundler'
Plugin 'tomasr/molokai'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'airblade/vim-gitgutter' " show git diff in gutter
Plugin 'mxw/vim-jsx'

call vundle#end()

" allow usage of mouse
if has("mouse")
  set mouse=a
endif

" tab completion
set wildmode=longest,list
set wildmenu

" display tabs and trailing whitespace
set listchars=trail:·,tab:→→
set list

" expand tabs to spaces
set expandtab
set tabstop=2
set softtabstop=2

" use two spaces for indentation
set shiftwidth=2

" case insensitive search
set ignorecase
set smartcase

" incremental search with term highlighting
set incsearch
set hlsearch

" enable autoindent
set autoindent
set smartindent

" syntax highlighting
syntax enable

" use molokai color scheme
let g:molokai_original=1
let g:rehash256=1
set t_Co=256
colorscheme molokai

let g:airline_theme="luna"
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1 " smarter tab line

set laststatus=2 " always show status line
set cursorline " highlight the current line
set number " show line numbers

" remove "|" character from column separating vertical splits
set fillchars+=vert:\ 
hi VertSplit ctermbg=37

" show more information command bar
set showcmd
set ruler

" filetypes
filetype plugin indent on

autocmd BufNewFile,BufReadPost *.json set filetype=json
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" unmap arrow keys
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

" easier split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" easier access to esc key
inoremap jj <ESC>

" use mapleader as space
let mapleader = "\<Space>"

" spell checking
map <F4> :set spell!<CR><Bar>:echo "Spell Check: " . strpart("OffOn", 3 * &spell, 3)<CR>

" toggle :set paste / :set nopaste
set pastetoggle=<F10>

" toogle NERDTree
" map <C-n> :NERDTreeToggle<CR>
map <C-n> <plug>NERDTreeTabsToggle<CR>
let NERDTreeMinimalUI=1
let NERDTreeMouseMode=2

" allow jsx syntax in js files
let g:jsx_ext_required = 0

" use eslint for javascript
let g:syntastic_javascript_checkers = ['eslint']

